### PR TITLE
Fix a rare case where fragment.getView return null when view is still…

### PR DESCRIPTION
**Pull request by vincent-paing**
- Fix a rare NullPointerException when loading a view is taking too long on lower end devices

### CODE REVIEW

**Comment by crosswall** [comment]
thanks @vincent-paing , i will quick build it

**Comment by crosswall** [comment]
and i think should better compatibility mode

```code
Object object = mPager.getAdapter().instantiateItem(mPager, loopCounter);
                    //Elevate the Center View if it's the selected position and de-elevate the left and right fragment

                    if(object instanceof Fragment){
                        Fragment fragment = (Fragment) object;
                        if (loopCounter == position) {
                            ViewCompat.setElevation(fragment.getView(), 8.0f);
                        } else {
                            ViewCompat.setElevation(fragment.getView(), 0.0f);
                        }
                    }else{
                        View view = (View) object;
                        if (loopCounter == position) {
                            ViewCompat.setElevation(view, 8.0f);
                        } else {
                            ViewCompat.setElevation(view, 0.0f);
                        }
                    }
```

**Comment by vincent-paing** [comment]
Yeah it looks better since it will be compatible without FragmentPagerAdapter 👍

**Comment by crosswall** [comment]
Hi @vincent-paing ,Maybe you can write a demo, let more people learn to use

**Comment by vincent-paing** [comment]
@crosswall Sure, I'll do a demo

**Pull request merged**
